version: '0.0.{build}'
configuration:
- Release
platform: Any CPU
before_build:
- dotnet tool restore
- dotnet restore -v Minimal
build_script:
- dotnet build
after_build:
- dotnet pack -p:PackageVersion=0.0.1 --no-build
test_script:
- dotnet test
deploy:
  - provider: NuGet
    api_key: 
      secure: 21JG9udvahkZg9q7TGQcw5ppXiNbkMKI4VUsWeGBbnapaOPBSX6noqlxs/w3EgDM
